global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: DEBUG
  format: common

accessLog:
  format: common

api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entrypoint:
          to: https
          scheme: https
  https:
    # we can't use default 443 because of NAS-4900 on images < v2.4.0
    address: :3443

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/config.yml
