version: '3'

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      # we can't use default 443 because of NAS-4900 on images < v2.4.0
      - "3443:3443"
      # Traefik dashboard and API, insecure
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/:/etc/traefik/:ro

  gooddata-cn-ce:
    image: gooddata/gooddata-cn-ce:latest
    container_name: gooddata-cn-ce
    environment:
      LICENSE_AND_PRIVACY_POLICY_ACCEPTED: "YES"
      # we can't use default port because of NAS-4900 on images < v2.4.0
      GDCN_PUBLIC_URL: https://analytics.example.com:3443
    networks:
      - backend
    ports:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gooddata-cn-ce.rule=Host(`analytics.example.com`)"
      - "traefik.http.routers.gooddata-cn-ce.tls=true"
    volumes:
      - "gd-cn-data:/data:rw"

volumes:
  gd-cn-data:

networks:
  frontend:
  backend:
